### ISSUE TITLE
AssertionError: -> table does not match expected size

### ISSUE THREAD

**Issue by toreog** [Brandon-Rozek/vspursuer#28]
Hi Brandon!

I get an AssertionError in some cases. The following output should be obtainable if you set MaGIC to stop when reaching size 6 and load the logic B with the assertion axiom - a -> ((a -> b) -> b) - and the contraction axiom - (a -> (a -> b)) -> (a -> b).

./vspursuer.py -i ../bwa          
Traceback (most recent call last):
  File "/Users/mctore/vspursuer/./vspursuer.py", line 22, in <module>
    solutions = parse_matrices(SourceFile(data_file))
  File "/Users/mctore/vspursuer/parse_magic.py", line 220, in parse_matrices
    processed = process_implications(infile, current_model_parts)
  File "/Users/mctore/vspursuer/parse_magic.py", line 298, in process_implications
    mimplication = parse_single_dyadic_connective(infile, "→", current_model_parts.size)
                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mctore/vspursuer/parse_magic.py", line 579, in parse_single_dyadic_connective
    assert len(table) == (size + 1)**2, f"{symbol} table does not match expected size at line {infile.current_line}"
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: → table does not match expected size at line 102

**Comment by Brandon-Rozek** [comment]
I was not able to reproduce this. I think you mentioned before that you run a different version of magic? I use the version from https://github.com/arranstewart/magic

**Comment by Brandon-Rozek** [comment]
Here's the result I got (skipping the null-results):
```
Parsed 1291 matrices
Model 6.2.1.1.12 has the variable sharing property.
Subalgebra 1: {2}
Subalgebra 2: {3}

=========================
Model Name: 6.2.1.1.12
Carrier Set: {1, 4, 2, 5, 0, 3}
Designated Values: {1, 4, 2, 5, 3}
 ∨ | 0 1 2 3 4 5
---+-------------
 0 | 0 1 2 3 4 5
 1 | 1 1 2 3 4 5
 2 | 2 2 2 4 4 5
 3 | 3 3 4 3 4 5
 4 | 4 4 4 4 4 5
 5 | 5 5 5 5 5 5

 ∧ | 0 1 2 3 4 5
---+-------------
 0 | 0 0 0 0 0 0
 1 | 0 1 1 1 1 1
 2 | 0 1 2 1 2 2
 3 | 0 1 1 3 3 3
 4 | 0 1 2 3 4 4
 5 | 0 1 2 3 4 5

 ¬ | 0 1 2 3 4 5
---+-------------
   | 5 4 2 3 1 0

 → | 0 1 2 3 4 5
---+-------------
 0 | 5 5 5 5 5 5
 1 | 0 1 2 3 4 5
 2 | 0 0 2 0 2 2
 3 | 0 0 0 3 3 3
 4 | 0 0 0 0 1 1
 5 | 0 0 0 0 0 1

=========================

Model 6.2.1.1.29 has the variable sharing property.
Subalgebra 1: {2}
Subalgebra 2: {3}

=========================
Model Name: 6.2.1.1.29
Carrier Set: {1, 4, 2, 5, 0, 3}
Designated Values: {1, 4, 2, 5, 3}
 ∨ | 0 1 2 3 4 5
---+-------------
 0 | 0 1 2 3 4 5
 1 | 1 1 2 3 4 5
 2 | 2 2 2 4 4 5
 3 | 3 3 4 3 4 5
 4 | 4 4 4 4 4 5
 5 | 5 5 5 5 5 5

 ∧ | 0 1 2 3 4 5
---+-------------
 0 | 0 0 0 0 0 0
 1 | 0 1 1 1 1 1
 2 | 0 1 2 1 2 2
 3 | 0 1 1 3 3 3
 4 | 0 1 2 3 4 4
 5 | 0 1 2 3 4 5

 ¬ | 0 1 2 3 4 5
---+-------------
   | 5 4 2 3 1 0

 → | 0 1 2 3 4 5
---+-------------
 0 | 5 5 5 5 5 5
 1 | 0 1 2 3 4 5
 2 | 0 0 2 0 2 4
 3 | 0 0 0 3 3 4
 4 | 0 0 0 0 1 4
 5 | 0 0 0 0 0 1

=========================

Model 6.2.1.1.30 has the variable sharing property.
Subalgebra 1: {2}
Subalgebra 2: {3}

=========================
Model Name: 6.2.1.1.30
Carrier Set: {1, 4, 2, 5, 0, 3}
Designated Values: {1, 4, 2, 5, 3}
 → | 0 1 2 3 4 5
---+-------------
 0 | 5 5 5 5 5 5
 1 | 0 1 2 3 4 5
 2 | 0 0 2 0 4 4
 3 | 0 0 0 3 4 4
 4 | 0 0 0 0 4 4
 5 | 0 0 0 0 0 1

 ∧ | 0 1 2 3 4 5
---+-------------
 0 | 0 0 0 0 0 0
 1 | 0 1 1 1 1 1
 2 | 0 1 2 1 2 2
 3 | 0 1 1 3 3 3
 4 | 0 1 2 3 4 4
 5 | 0 1 2 3 4 5

 ¬ | 0 1 2 3 4 5
---+-------------
   | 5 4 2 3 1 0

 ∨ | 0 1 2 3 4 5
---+-------------
 0 | 0 1 2 3 4 5
 1 | 1 1 2 3 4 5
 2 | 2 2 2 4 4 5
 3 | 3 3 4 3 4 5
 4 | 4 4 4 4 4 5
 5 | 5 5 5 5 5 5

=========================

Model 6.2.1.1.51 has the variable sharing property.
Subalgebra 1: {2}
Subalgebra 2: {3}

=========================
Model Name: 6.2.1.1.51
Carrier Set: {1, 4, 2, 5, 0, 3}
Designated Values: {1, 4, 2, 5, 3}
 ∨ | 0 1 2 3 4 5
---+-------------
 0 | 0 1 2 3 4 5
 1 | 1 1 2 3 4 5
 2 | 2 2 2 4 4 5
 3 | 3 3 4 3 4 5
 4 | 4 4 4 4 4 5
 5 | 5 5 5 5 5 5

 → | 0 1 2 3 4 5
---+-------------
 0 | 5 5 5 5 5 5
 1 | 0 1 2 3 4 5
 2 | 0 0 2 0 2 5
 3 | 0 0 0 3 3 4
 4 | 0 0 0 0 1 4
 5 | 0 0 0 0 0 2

 ¬ | 0 1 2 3 4 5
---+-------------
   | 5 4 2 3 1 0

 ∧ | 0 1 2 3 4 5
---+-------------
 0 | 0 0 0 0 0 0
 1 | 0 1 1 1 1 1
 2 | 0 1 2 1 2 2
 3 | 0 1 1 3 3 3
 4 | 0 1 2 3 4 4
 5 | 0 1 2 3 4 5

=========================

Model 6.2.1.1.54 has the variable sharing property.
Subalgebra 1: {2}
Subalgebra 2: {3}

=========================
Model Name: 6.2.1.1.54
Carrier Set: {1, 4, 2, 5, 0, 3}
Designated Values: {1, 4, 2, 5, 3}
 ∨ | 0 1 2 3 4 5
---+-------------
 0 | 0 1 2 3 4 5
 1 | 1 1 2 3 4 5
 2 | 2 2 2 4 4 5
 3 | 3 3 4 3 4 5
 4 | 4 4 4 4 4 5
 5 | 5 5 5 5 5 5

 ∧ | 0 1 2 3 4 5
---+-------------
 0 | 0 0 0 0 0 0
 1 | 0 1 1 1 1 1
 2 | 0 1 2 1 2 2
 3 | 0 1 1 3 3 3
 4 | 0 1 2 3 4 4
 5 | 0 1 2 3 4 5

 ¬ | 0 1 2 3 4 5
---+-------------
   | 5 4 2 3 1 0

 → | 0 1 2 3 4 5
---+-------------
 0 | 5 5 5 5 5 5
 1 | 0 1 2 3 4 5
 2 | 0 0 2 0 4 5
 3 | 0 0 0 3 4 4
 4 | 0 0 0 0 4 4
 5 | 0 0 0 0 0 2

=========================
Model 6.2.1.1.65 has the variable sharing property.
Subalgebra 1: {2}
Subalgebra 2: {3}

=========================
Model Name: 6.2.1.1.65
Carrier Set: {1, 4, 2, 5, 0, 3}
Designated Values: {1, 4, 2, 5, 3}
 ∨ | 0 1 2 3 4 5
---+-------------
 0 | 0 1 2 3 4 5
 1 | 1 1 2 3 4 5
 2 | 2 2 2 4 4 5
 3 | 3 3 4 3 4 5
 4 | 4 4 4 4 4 5
 5 | 5 5 5 5 5 5

 ∧ | 0 1 2 3 4 5
---+-------------
 0 | 0 0 0 0 0 0
 1 | 0 1 1 1 1 1
 2 | 0 1 2 1 2 2
 3 | 0 1 1 3 3 3
 4 | 0 1 2 3 4 4
 5 | 0 1 2 3 4 5

 ¬ | 0 1 2 3 4 5
---+-------------
   | 5 4 2 3 1 0

 → | 0 1 2 3 4 5
---+-------------
 0 | 5 5 5 5 5 5
 1 | 0 1 2 3 4 5
 2 | 0 0 2 0 2 5
 3 | 0 0 0 3 3 5
 4 | 0 0 0 0 1 5
 5 | 0 0 0 0 0 4

=========================

Model 6.2.1.1.66 has the variable sharing property.
Subalgebra 1: {2}
Subalgebra 2: {3}

=========================
Model Name: 6.2.1.1.66
Carrier Set: {1, 4, 2, 5, 0, 3}
Designated Values: {1, 4, 2, 5, 3}
 ∨ | 0 1 2 3 4 5
---+-------------
 0 | 0 1 2 3 4 5
 1 | 1 1 2 3 4 5
 2 | 2 2 2 4 4 5
 3 | 3 3 4 3 4 5
 4 | 4 4 4 4 4 5
 5 | 5 5 5 5 5 5

 ∧ | 0 1 2 3 4 5
---+-------------
 0 | 0 0 0 0 0 0
 1 | 0 1 1 1 1 1
 2 | 0 1 2 1 2 2
 3 | 0 1 1 3 3 3
 4 | 0 1 2 3 4 4
 5 | 0 1 2 3 4 5

 ¬ | 0 1 2 3 4 5
---+-------------
   | 5 4 2 3 1 0

 → | 0 1 2 3 4 5
---+-------------
 0 | 5 5 5 5 5 5
 1 | 0 1 2 3 4 5
 2 | 0 0 2 0 4 5
 3 | 0 0 0 3 4 5
 4 | 0 0 0 0 4 5
 5 | 0 0 0 0 0 4

=========================
Model 6.2.1.1.77 has the variable sharing property.
Subalgebra 1: {2}
Subalgebra 2: {3}

=========================
Model Name: 6.2.1.1.77
Carrier Set: {1, 4, 2, 5, 0, 3}
Designated Values: {1, 4, 2, 5, 3}
 ∨ | 0 1 2 3 4 5
---+-------------
 0 | 0 1 2 3 4 5
 1 | 1 1 2 3 4 5
 2 | 2 2 2 4 4 5
 3 | 3 3 4 3 4 5
 4 | 4 4 4 4 4 5
 5 | 5 5 5 5 5 5

 ∧ | 0 1 2 3 4 5
---+-------------
 0 | 0 0 0 0 0 0
 1 | 0 1 1 1 1 1
 2 | 0 1 2 1 2 2
 3 | 0 1 1 3 3 3
 4 | 0 1 2 3 4 4
 5 | 0 1 2 3 4 5

 ¬ | 0 1 2 3 4 5
---+-------------
   | 5 4 2 3 1 0

 → | 0 1 2 3 4 5
---+-------------
 0 | 5 5 5 5 5 5
 1 | 0 1 2 3 4 5
 2 | 0 0 2 0 2 5
 3 | 0 0 0 3 3 5
 4 | 0 0 0 0 1 5
 5 | 0 0 0 0 0 5

=========================

Model 6.2.1.1.78 has the variable sharing property.
Subalgebra 1: {2}
Subalgebra 2: {3}

=========================
Model Name: 6.2.1.1.78
Carrier Set: {1, 4, 2, 5, 0, 3}
Designated Values: {1, 4, 2, 5, 3}
 ∨ | 0 1 2 3 4 5
---+-------------
 0 | 0 1 2 3 4 5
 1 | 1 1 2 3 4 5
 2 | 2 2 2 4 4 5
 3 | 3 3 4 3 4 5
 4 | 4 4 4 4 4 5
 5 | 5 5 5 5 5 5

 ∧ | 0 1 2 3 4 5
---+-------------
 0 | 0 0 0 0 0 0
 1 | 0 1 1 1 1 1
 2 | 0 1 2 1 2 2
 3 | 0 1 1 3 3 3
 4 | 0 1 2 3 4 4
 5 | 0 1 2 3 4 5

 ¬ | 0 1 2 3 4 5
---+-------------
   | 5 4 2 3 1 0

 → | 0 1 2 3 4 5
---+-------------
 0 | 5 5 5 5 5 5
 1 | 0 1 2 3 4 5
 2 | 0 0 2 0 4 5
 3 | 0 0 0 3 4 5
 4 | 0 0 0 0 4 5
 5 | 0 0 0 0 0 5

=========================

Tested 1291 models, 9 of which satisfy VSP
```

**Comment by toreog** [comment]
Strange! I tried with a fresh (and unmodified) instalation of MaGIC (both 2.4 and 2.5) and got the same result. I'll try to look into this next week.

Thanks for the output. I've compared it to what MaGIC outputs when set-up the way I've been doing (in the relevancetest.bat file). It spits out the 9 models displayed above, but in addition the following two (I only display the implication matrices, since the rest is identical in all models):

-> | 0 1 2 3 4 5
---+------------
0 | 5 5 5 5 5 5
1 | 0 1 2 3 4 5
2 | 0 0 2 0 2 4
3 | 0 0 0 3 3 5
4 | 0 0 0 0 1 4
5 | 0 0 0 0 0 3

-> | 0 1 2 3 4 5
---+------------
0 | 5 5 5 5 5 5
1 | 0 1 2 3 4 5
2 | 0 0 2 0 4 4
3 | 0 0 0 3 4 5
4 | 0 0 0 0 4 4
5 | 0 0 0 0 0 3

Maybe these two models are isomorphic to one of the nine (a bit hard to figure out which, I must confess), but got be wondering if vspursuer applies a filter for isomorphic models?

**Comment by Brandon-Rozek** [comment]
VSPursuer doesn't currently check for any isomorphic models. In the version of MaGIC that I'm running part of the output tells me that it omits 112 isomorphic models. I also am not able to tell if the ones you presented are isomorphic to any of the 9.

I think I'm running an older version of MaGIC. When I open it up it says v2.1. I'll try to find and get running the newer versions over the next few days.

**Comment by toreog** [comment]
The latest version (2.5) can be downloaded from Slaney's web-page: https://users.cecs.anu.edu.au/~jks/software/. Unfortunatly, Slaney seems not to update the text displaying the version and so version 2.5 will still display "This is MaGIC Version 2.1, released May 1993." Do let me know if you get different results than I have. Again, very excited that you're working on this!!

Best, Tore

**Comment by Brandon-Rozek** [comment]
After freshly installing MaGIC and VSPurser, Tore and I weren't able to reproduce this error. If you come across this again, feel free to reopen this ticket.
